### ISSUE TITLE
Região Metropolitana Vale do Paraíba e Litoral Norte

### ISSUE THREAD

**Issue by d116626** [pjssilva/Robot-dance#1]
Olá Paulo,

Trabalho como Assessor de um Deputado da Região Metropolitana Vale do Paraíba e Litoral Norte. Tentei rodar seus códigos porem não obtive sucesso, Julia é novo para mim. Gostaria de saber se teria como rodar o sistema e saber o perfil de controle e relaxamento para algumas cidades da região do Vale.
Estou em contato com alguns gestores da região do Vale e gostaria de colocá-lo em contato com eles, poderia me passar seu contato?

Parabéns pelo excelente trabalho!

**Comment by pjssilva** [comment]
Olá. Infelizmente o código depende do Julia, de fato isso foi fundamental para colocarmos ele para funcionar em tão pouco tempo. Hoje e no final de semana vou trabalhar para criar uma especificação dos arquivos de entrada e de como instalar o Julia para que ele possa ser rodado por terceiros. Espero que isso lhe ajude. Uma vez que isso estiver pronto será mais simples para você entender o que precisa para "rodar".

**Comment by d116626** [comment]
Que ótimo! Nesse meio tempo teria como você mesmo rodar pra algumas cidades do vale (São José dos Campos, São Sebastião, Jacareí, Caraguatatuba, Taubaté)? Muito obrigado pela atenção!

**Comment by pjssilva** [comment]
Diego, como disse vou trabahar no final de semana sobre isso. Não dá para rodar nada "nesse meio tempo", até porque o trabalho de levantar os dados (e até de explicar que dados têm que ser levantados) é grande. Não é algo que dá para rodar sem uma preparação, entende? Tenho que priorizar o meu tempo e nesse caso a prioridade é colocar o código mais próximo de algo que possa ser rodado por terceiros.

**Comment by d116626** [comment]
Tudo bem, estarei aguardando. Obrigado!

**Comment by pjssilva** [comment]
Oi. Coloquei uma versão nova que é mais fácil de rodar com arquivos bem definidos de entrada. Dê uma olhada e veja se ajuda.

**Comment by pjssilva** [comment]
Como não hoube mais comentários vou considerar o "problema" como resolvido.
